---
name: "Release Automation"

"on":
  push:
    branches:
      - main
permissions:
  # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
  contents: write


jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: elgohr/Github-Release-Action@v5
        with:
          title: "Release ${{ github.ref }}"
          prerelease: false
        if: startsWith(github.ref, 'refs/tags/v')
  latest-release:
    name: "Dev Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: elgohr/Github-Release-Action@v5
        with:
          title: Dev release
          tag: "dev"
          prerelease: true
        if: ${{ github.ref == 'refs/heads/main'}}
