---
name: Rust Testing
"on":
  push:

jobs:
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
      - run: |
          cargo test
          cargo test --release
          cargo clippy --all-targets
