---
name: Rust Testing
"on":
  push:

jobs:
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
      - uses: actions-rs/cargo@v1
        with:
          command: test
